create database if not exists productos;
GRANT ALL PRIVILEGES ON productos.* TO coder;
FLUSH PRIVILEGES;
CREATE TABLE PRODUCTOS (
  ID_PRODUCTO int AUTO_INCREMENT,
  TITULO VARCHAR (50) NOT NULL,
  PRECIO DECIMAL (15, 2) NOT NULL,
  IMAGEN VARCHAR(255) NOT NULL
);